formatter: md
output:
  file: README.md
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    # AWS Secret with LOGIC

    Terraform module for easily creating a secret in AWS Secrets Manager.

    {{ .Content }}

    ---

    <p align="center"><a href="https://withlogic.co">Built with LOGIC</a></p>
    <!-- END_TF_DOCS -->
